config = {'vocab_path': '/data/kdgyun425/parameters/bpe.vocab',
          'codes_path': '/data/kdgyun425/parameters/bpe.code',
          'train_datasets': ['/data/kdgyun425/datasets/ConvAI2/train_self_revised_no_cands.txt',
                             '/data/kdgyun425/datasets/ConvAI2/train_self_original_no_cands.txt'],
          'valid_datasets': ['/data/kdgyun425/datasets/ConvAI2/valid_self_revised_no_cands.txt',
                             '/data/kdgyun425/datasets/ConvAI2/valid_self_original_no_cands.txt'],
          'test_datasets': None,
          'batch_size': 200,
          'device': 'cuda:1',
          'hdd': 300,
          'layers': 3,
          'lr': 0.001,
          'dr': 0.2,
          'tr': 0.5,
          'position': False,
          'clip': 10.0,
          'epochs': 100,
          'load_path': None,
          'save_path': '/data/kdgyun425/mem2seq-persona/save/',
          'version': 1,
         }
